// src/utils/stackKnowledge.js

export const stackKnowledge = {
  react: {
    pros: ['Component-based architecture', 'Huge ecosystem', 'Virtual DOM for performance', 'Strong community & hiring pool'],
    cons: ['Boilerplate-heavy for large apps', 'Frequent ecosystem churn', 'No opinionated structure'],
    type: 'frontend',
    pairs_well_with: ['nodejs', 'express', 'firebase', 'supabase', 'nextjs'],
    conflicts_with: ['vue', 'svelte'],
  },
  vue: {
    pros: ['Gentle learning curve', 'Two-way data binding', 'Well-structured documentation', 'Great for small teams'],
    cons: ['Smaller ecosystem than React', 'Less enterprise adoption', 'Plugin quality varies'],
    type: 'frontend',
    pairs_well_with: ['nodejs', 'express', 'firebase'],
    conflicts_with: ['react', 'svelte', 'nextjs'],
  },
  nextjs: {
    pros: ['SSR & SSG out of the box', 'File-based routing', 'Built-in API routes', 'Vercel-optimized deployment'],
    cons: ['Opinionated structure', 'Cold start issues on serverless', 'Larger bundle than plain React'],
    type: 'frontend',
    pairs_well_with: ['vercel', 'postgresql', 'mongodb', 'supabase', 'firebase-auth', 'clerk'],
    conflicts_with: ['react', 'vue', 'svelte'],
  },
  svelte: {
    pros: ['No virtual DOM — compiles to vanilla JS', 'Tiny bundle size', 'Simple reactivity model'],
    cons: ['Smaller ecosystem', 'Fewer UI libraries', 'Less enterprise adoption'],
    type: 'frontend',
    pairs_well_with: ['nodejs', 'express', 'firebase'],
    conflicts_with: ['react', 'vue', 'nextjs'],
  },
  nodejs: {
    pros: ['JavaScript everywhere', 'Non-blocking I/O', 'Massive npm ecosystem', 'Great for real-time apps'],
    cons: ['Single-threaded (CPU-intensive tasks suffer)', 'Callback complexity without async/await discipline', 'Not ideal for heavy computation'],
    type: 'backend',
    pairs_well_with: ['react', 'vue', 'svelte', 'mongodb', 'postgresql', 'express'],
    conflicts_with: ['django', 'fastapi'],
  },
  express: {
    pros: ['Minimal and unopinionated', 'Fast to prototype', 'Huge middleware ecosystem'],
    cons: ['No built-in structure — scales poorly without discipline', 'Manual error handling', 'No built-in TypeScript'],
    type: 'backend',
    pairs_well_with: ['react', 'vue', 'mongodb', 'postgresql', 'nodejs'],
    conflicts_with: ['django', 'fastapi'],
  },
  django: {
    pros: ['Batteries included (ORM, admin, auth)', 'Opinionated — enforces structure', 'Excellent for content-heavy apps'],
    cons: ['Python-only', 'Monolithic by default', 'Steeper React integration', 'Slower than async frameworks'],
    type: 'backend',
    pairs_well_with: ['postgresql', 'vue', 'react'],
    conflicts_with: ['nodejs', 'express', 'fastapi'],
  },
  fastapi: {
    pros: ['Async-first', 'Auto-generated docs (Swagger)', 'Type-safe with Pydantic', 'High performance'],
    cons: ['Python ecosystem', 'Smaller community than Django/Express', 'No built-in ORM'],
    type: 'backend',
    pairs_well_with: ['postgresql', 'mongodb', 'react', 'vue'],
    conflicts_with: ['nodejs', 'express', 'django'],
  },
  mongodb: {
    pros: ['Flexible schema (JSON-like documents)', 'Horizontal scaling', 'Great for rapid iteration', 'Built-in replication'],
    cons: ['No ACID transactions by default', 'Poor for complex relational queries', 'Data duplication risk'],
    type: 'database',
    pairs_well_with: ['nodejs', 'express', 'fastapi', 'react'],
    conflicts_with: ['postgresql'],
  },
  postgresql: {
    pros: ['ACID compliant', 'Powerful relational queries', 'JSON support', 'Battle-tested at scale'],
    cons: ['Requires schema design upfront', 'Heavier ops overhead', 'Vertical scaling by default'],
    type: 'database',
    pairs_well_with: ['django', 'fastapi', 'nodejs', 'nextjs', 'supabase'],
    conflicts_with: ['mongodb'],
  },
  firebase: {
    pros: ['Real-time database', 'No backend needed', 'Built-in offline support', 'Easy scaling'],
    cons: ['Vendor lock-in', 'Complex queries are painful', 'Costly at scale', 'No SQL joins'],
    type: 'database',
    pairs_well_with: ['react', 'vue', 'nextjs', 'firebase-auth'],
    conflicts_with: ['postgresql', 'mongodb', 'supabase'],
  },
  supabase: {
    pros: ['Open-source Firebase alternative', 'PostgreSQL under the hood', 'Real-time subscriptions', 'Built-in auth'],
    cons: ['Younger ecosystem', 'Self-hosting complexity', 'Some features still maturing'],
    type: 'database',
    pairs_well_with: ['react', 'nextjs', 'vue', 'clerk'],
    conflicts_with: ['firebase', 'mongodb'],
  },
  'firebase-auth': {
    pros: ['Drop-in auth solution', 'Social login built-in', 'Integrates seamlessly with Firestore', 'Free tier is generous'],
    cons: ['Vendor lock-in', 'Limited customization', 'Firebase-only ecosystem'],
    type: 'auth',
    pairs_well_with: ['react', 'vue', 'firebase', 'nextjs'],
    conflicts_with: ['auth0', 'clerk'],
  },
  auth0: {
    pros: ['Enterprise-ready', 'Highly customizable', 'Supports any backend', 'MFA & SSO built-in'],
    cons: ['Expensive at scale', 'Configuration complexity', 'Overkill for small apps'],
    type: 'auth',
    pairs_well_with: ['react', 'nodejs', 'express', 'nextjs', 'django'],
    conflicts_with: ['firebase-auth', 'clerk'],
  },
  clerk: {
    pros: ['Best-in-class DX', 'Pre-built UI components', 'Next.js native', 'Generous free tier'],
    cons: ['Relatively new', 'Vendor lock-in', 'Less customizable than Auth0'],
    type: 'auth',
    pairs_well_with: ['nextjs', 'react', 'supabase', 'postgresql'],
    conflicts_with: ['firebase-auth', 'auth0'],
  },
  vercel: {
    pros: ['Zero-config deployments', 'Global CDN', 'Preview URLs per branch', 'Optimized for Next.js'],
    cons: ['Serverless function limits', 'Expensive for high traffic', 'Vendor lock-in'],
    type: 'hosting',
    pairs_well_with: ['nextjs', 'react', 'supabase', 'postgresql'],
    conflicts_with: ['netlify', 'aws', 'railway'],
  },
  netlify: {
    pros: ['Simple CI/CD', 'Built-in form handling', 'Generous free tier', 'Edge functions'],
    cons: ['Serverless function cold starts', 'Less optimized than Vercel for Next.js', 'Limited compute'],
    type: 'hosting',
    pairs_well_with: ['react', 'vue', 'svelte', 'firebase'],
    conflicts_with: ['vercel', 'aws', 'railway'],
  },
  aws: {
    pros: ['Infinite scalability', 'Full control over infrastructure', 'Every service imaginable', 'Enterprise standard'],
    cons: ['Steep learning curve', 'Complex pricing', 'Over-engineered for small projects'],
    type: 'hosting',
    pairs_well_with: ['nodejs', 'django', 'fastapi', 'postgresql', 'mongodb'],
    conflicts_with: ['vercel', 'netlify', 'railway'],
  },
  railway: {
    pros: ['Heroku-like simplicity', 'Supports any language/framework', 'Easy database provisioning', 'Affordable'],
    cons: ['Smaller ecosystem', 'Less mature than AWS', 'Fewer regions'],
    type: 'hosting',
    pairs_well_with: ['nodejs', 'express', 'django', 'fastapi', 'postgresql', 'mongodb'],
    conflicts_with: ['vercel', 'netlify', 'aws'],
  },
}